#!/usr/bin/env python3
"""
fetch-packs.py — pulls ALL available Open5e content beyond the core 5.1 SRD
(which lives in srd-bulk.js, regenerated by fetch-open5e.py) and writes
lazy-loadable content packs:

    data/packs/manifest.js     window.CODEX_PACK_MANIFEST  (tiny, loaded at boot)
    data/packs/<pack-id>.js    window.CODEX_PACKS["<id>"]  (loaded on demand)

Sources:
    - Open5e v1 API — every document EXCEPT wotc-srd: Kobold Press books
      (Tome of Beasts 1/2/3/2023, Creature Codex, Deep Magic, Vault of Magic,
      Tome of Heroes, ...), Level Up Advanced 5e, Black Flag SRD, Tal'Dorei,
      Open5e originals. One pack per source document.
    - Open5e v2 API — System Reference Document 5.2 (the D&D 2024 rules,
      CC BY 4.0) as the "srd-2024" pack.

Usage:
    python data/fetch-packs.py
"""
import importlib.util
import json
import re
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).parent
API1 = "https://api.open5e.com/v1"
API2 = "https://api.open5e.com/v2"
UA = "Codex-fetch/1.0 (+https://example.local)"

# Reuse the v1 transforms from fetch-open5e.py (hyphenated filename -> importlib).
_spec = importlib.util.spec_from_file_location("fetch_open5e", HERE / "fetch-open5e.py")
base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(base)

first_sentence = base.first_sentence
title_case = base.title_case

# ─── Pack registry ──────────────────────────────────────────────────────────
# slug: (label, group, badge, edition)
PACK_INFO = {
    "srd-2024":  ("D&D 2024 — SRD 5.2",                       "D&D 2024 Rules",        "2024",   "5e-2024"),
    "srd-2014-x": ("SRD 5.1 — Gear & Item Variants",          "D&D 2014 Rules",        "5.1+",   "5e-2014"),
    "spells-that-dont-suck": ("Spells That Don't Suck",       "Open5e Community",      "STDS",   "5e-2014"),
    "a5e":       ("Level Up: Advanced 5e",                     "EN Publishing (A5E)",   "A5E",    "a5e"),
    "menagerie": ("A5E Monstrous Menagerie",                   "EN Publishing (A5E)",   "A5E MM", "a5e"),
    "blackflag": ("Black Flag SRD (Tales of the Valiant)",     "Kobold Press",          "ToV",    "blackflag"),
    "tob":       ("Tome of Beasts",                            "Kobold Press",          "ToB",    "5e-2014"),
    "tob-2023":  ("Tome of Beasts (2023 edition)",             "Kobold Press",          "ToB'23", "5e-2014"),
    "tob2":      ("Tome of Beasts 2",                          "Kobold Press",          "ToB2",   "5e-2014"),
    "tob3":      ("Tome of Beasts 3",                          "Kobold Press",          "ToB3",   "5e-2014"),
    "cc":        ("Creature Codex",                            "Kobold Press",          "CC",     "5e-2014"),
    "dmag":      ("Deep Magic",                                "Kobold Press",          "DM",     "5e-2014"),
    "dmag-e":    ("Deep Magic Extended",                       "Kobold Press",          "DM+",    "5e-2014"),
    "vom":       ("Vault of Magic",                            "Kobold Press",          "VoM",    "5e-2014"),
    "toh":       ("Tome of Heroes",                            "Kobold Press",          "ToH",    "5e-2014"),
    "kp":        ("Kobold Press Compilation",                  "Kobold Press",          "KP",     "5e-2014"),
    "warlock":   ("Warlock Archives",                          "Kobold Press",          "WZ",     "5e-2014"),
    "taldorei":  ("Tal'Dorei Campaign Setting",                "Green Ronin",           "TD",     "5e-2014"),
    "o5e":       ("Open5e Original Content",                   "Open5e Community",      "O5e",    "5e-2014"),
}
# Display order for the manifest (groups stay together in the UI):
PACK_ORDER = ["srd-2024", "srd-2014-x", "a5e", "menagerie", "blackflag", "tob", "tob-2023",
              "tob2", "tob3", "cc", "dmag", "dmag-e", "vom", "toh", "kp", "warlock",
              "taldorei", "spells-that-dont-suck", "o5e"]

# v1 endpoint -> app tab
V1_ENDPOINTS = {
    "monsters":   "monsters",
    "spells":     "spells",
    "magicitems": "items",
    "weapons":    "weapons",
    "armor":      "armor",
    "feats":      "feats",
    "backgrounds":"backgrounds",
    "races":      "races",
}

# ─── HTTP with retry + pagination ───────────────────────────────────────────

def get_json(url, tries=4):
    last = None
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/json"})
            with urllib.request.urlopen(req, timeout=120) as resp:
                return json.loads(resp.read())
        except Exception as e:  # noqa: BLE001 — retry any transport hiccup
            last = e
            time.sleep(2 * (attempt + 1))
    raise RuntimeError(f"GET failed after {tries} tries: {url} ({last})")


def fetch_all(url):
    """Follow `next` links until exhausted; return the concatenated results."""
    out = []
    while url:
        payload = get_json(url)
        out.extend(payload.get("results") or [])
        nxt = payload.get("next")
        # Open5e sometimes hands back http:// next-links; keep https.
        url = nxt.replace("http://", "https://") if nxt else None
        sys.stderr.write(f"    …{len(out)}\n")
    return out


# ─── v1 transforms not covered by fetch-open5e.py ───────────────────────────

def strip_md(s):
    return re.sub(r"\*\*_?|_?\*\*", "", s or "").replace("**", "").strip()


def md_traits(md):
    """Split a v1 markdown trait blob (**_Name._** text …) into display strings."""
    out = []
    if not md:
        return out
    parts = re.split(r"\*\*_?\s*([^*_]+?)\.?\s*_?\*\*", md)
    for i in range(1, len(parts) - 1, 2):
        name = parts[i].strip()
        text = first_sentence(parts[i + 1].strip(), 220)
        if name:
            out.append(f"{name}. {text}" if text else name)
    return out


def v1_race(r):
    asi_text = strip_md(r.get("asi_desc") or "").replace("Ability Score Increase.", "").strip()
    subraces = []
    for sr in r.get("subraces") or []:
        subraces.append({
            "name": sr.get("name", ""),
            "asiText": strip_md(sr.get("asi_desc") or "").replace("Ability Score Increase.", "").strip(),
            "blurb": first_sentence(sr.get("desc") or ""),
            "traits": md_traits(sr.get("traits") or ""),
        })
    traits = md_traits(r.get("traits") or "")
    for extra in ("vision", "alignment"):
        t = md_traits(r.get(extra) or "")
        traits.extend(t)
    speed = r.get("speed") or {}
    return {
        "name": r["name"],
        "size": r.get("size_raw") or "Medium",
        "speed": speed.get("walk", 30) if isinstance(speed, dict) else 30,
        "asiText": asi_text or "—",
        "blurb": first_sentence(r.get("desc") or ""),
        "traits": traits,
        "subraces": subraces,
    }


def v1_background(b):
    skills = [s.strip() for s in (b.get("skill_proficiencies") or "").split(",") if s.strip()]
    tools = [t.strip() for t in (b.get("tool_proficiencies") or "").split(",") if t.strip()]
    return {
        "name": b["name"],
        "skills": skills,
        "tools": tools,
        "languages": (b.get("languages") or "").strip(),
        "feature": (b.get("feature") or "").strip(),
        "blurb": first_sentence(b.get("desc") or b.get("feature_desc") or ""),
        "desc": (b.get("desc") or "").strip(),
    }


def v1_feat(f):
    effects = f.get("effects_desc") or []
    desc = (f.get("desc") or "").strip()
    if effects:
        desc = (desc + "\n\n" if desc else "") + "\n".join(f"• {e}" for e in effects)
    return {
        "name": f["name"],
        "prerequisite": (f.get("prerequisite") or "").replace("Prerequisite:", "").strip(),
        "blurb": first_sentence(f.get("desc") or (effects[0] if effects else "")),
        "desc": desc,
    }


V1_TRANSFORMS = {
    "monsters":    base.transform_monster,
    "spells":      base.transform_spell,
    "magicitems":  base.transform_item,
    "weapons":     base.transform_weapon,
    "armor":       base.transform_armor,
    "feats":       v1_feat,
    "backgrounds": v1_background,
    "races":       v1_race,
}


# ─── v2 (SRD 5.2 / D&D 2024) transforms ─────────────────────────────────────

def nm(v):
    """name of a {name,key} dict, else the raw value as string."""
    if isinstance(v, dict):
        return v.get("name") or ""
    return v or ""


def cr_display(cr):
    if cr is None:
        return "?"
    frac = {0.125: "1/8", 0.25: "1/4", 0.5: "1/2"}
    if cr in frac:
        return frac[cr]
    return str(int(cr)) if float(cr).is_integer() else str(cr)


def v2_creature(m):
    speed_all = m.get("speed_all") or m.get("speed") or {}
    speed = {}
    for k in ("walk", "fly", "swim", "climb", "burrow"):
        v = speed_all.get(k)
        if v:
            speed[k] = v
    if speed_all.get("hover"):
        speed["hover"] = True

    mods = m.get("modifiers") or {}
    saves_raw = m.get("saving_throws") or {}
    saves = {}
    long2short = {"strength": "str", "dexterity": "dex", "constitution": "con",
                  "intelligence": "int", "wisdom": "wis", "charisma": "cha"}
    for lk, sk in long2short.items():
        sv, mv = saves_raw.get(lk), mods.get(lk)
        if sv is not None and sv != mv:  # only proficient saves
            saves[sk] = sv

    senses = []
    for k, label in (("darkvision_range", "darkvision"), ("blindsight_range", "blindsight"),
                     ("tremorsense_range", "tremorsense"), ("truesight_range", "truesight")):
        if m.get(k):
            senses.append(f"{label} {m[k]} ft.")
    if m.get("passive_perception") is not None:
        senses.append(f"passive Perception {m['passive_perception']}")

    ri = m.get("resistances_and_immunities") or {}

    acts, bonus, reacts, legendary = [], [], [], []
    for a in m.get("actions") or []:
        item = {"name": a.get("name", ""), "desc": (a.get("desc") or "").strip()}
        t = a.get("action_type")
        if t == "BONUS_ACTION":
            bonus.append(item)
        elif t == "REACTION":
            reacts.append(item)
        elif t == "LEGENDARY_ACTION":
            legendary.append(item)
        else:
            acts.append(item)

    traits = [{"name": t.get("name", ""), "desc": (t.get("desc") or "").strip()}
              for t in (m.get("traits") or [])]

    envs = []
    for e in m.get("environments") or []:
        envs.append(nm(e) if isinstance(e, (dict, str)) else str(e))

    ab = m.get("ability_scores") or {}
    lang = m.get("languages") or {}
    img = m.get("illustration")
    if isinstance(img, dict):
        img = img.get("url") or ""

    desc = (m.get("desc") or "").strip()
    blurb = first_sentence(desc)
    if not blurb:
        if traits and traits[0]["desc"]:
            blurb = first_sentence(traits[0]["desc"])
        elif acts and acts[0]["desc"]:
            blurb = first_sentence(acts[0]["desc"])
        else:
            blurb = f"{nm(m.get('size'))} {nm(m.get('type'))}.".strip()

    return {
        "name": m["name"],
        "slug": m.get("key", ""),
        "size": nm(m.get("size")),
        "type": nm(m.get("type")),
        "subtype": m.get("subcategory") or "",
        "group": m.get("category") or "",
        "alignment": m.get("alignment") or "",
        "cr": cr_display(m.get("challenge_rating")),
        "crNum": m.get("challenge_rating") or 0,
        "hp": m.get("hit_points", 0),
        "hitDice": m.get("hit_dice") or "",
        "ac": m.get("armor_class", 0),
        "armorDesc": m.get("armor_detail") or "",
        "speed": speed,
        "stats": {sk: ab.get(lk, 10) for lk, sk in long2short.items()},
        "saves": saves,
        "perception": m.get("passive_perception"),
        "skills": m.get("skill_bonuses") or {},
        "vulnerabilities": ri.get("damage_vulnerabilities_display", ""),
        "resistances": ri.get("damage_resistances_display", ""),
        "immunities": ri.get("damage_immunities_display", ""),
        "conditionImmunities": ri.get("condition_immunities_display", ""),
        "senses": ", ".join(senses),
        "languages": (lang.get("as_string") if isinstance(lang, dict) else str(lang or "")) or "",
        "actions": acts,
        "bonusActions": bonus,
        "reactions": reacts,
        "legendaryDesc": "",
        "legendaryActions": legendary,
        "specialAbilities": traits,
        "spellList": [],
        "environments": envs,
        "img": (img or "").replace("http://", "https://"),
        "blurb": blurb,
        "desc": desc,
    }


CAST_TIME = {
    "action": "1 action", "bonus_action": "1 bonus action", "reaction": "1 reaction",
    "minute_1": "1 minute", "minutes_10": "10 minutes", "hour_1": "1 hour",
    "hours_8": "8 hours", "hours_12": "12 hours", "hours_24": "24 hours",
}


def v2_spell(s):
    comps = [c for c, k in (("V", "verbal"), ("S", "somatic"), ("M", "material")) if s.get(k)]
    cast = CAST_TIME.get(s.get("casting_time"), (s.get("casting_time") or "").replace("_", " "))
    if s.get("reaction_condition"):
        cast = f"{cast} ({s['reaction_condition']})"
    dur = (s.get("duration") or "").strip()
    return {
        "name": s["name"],
        "level": s.get("level", 0),
        "school": nm(s.get("school")),
        "cast": cast,
        "range": s.get("range_text") or "",
        "components": ", ".join(comps),
        "material": (s.get("material_specified") or "").strip(),
        "ritual": s.get("ritual") is True,
        "concentration": s.get("concentration") is True,
        "duration": title_case(dur),
        "classes": [nm(c) for c in (s.get("classes") or [])],
        "blurb": first_sentence(s.get("desc") or ""),
        "desc": (s.get("desc") or "").strip(),
        "higher_level": (s.get("higher_level") or "").strip(),
    }


def v2_magicitem(it):
    desc = (it.get("desc") or "").strip()
    blurb = desc.split("\n")[0]
    if len(blurb) > 220:
        blurb = blurb[:219].rstrip() + "…"
    return {
        "name": it["name"],
        "rarity": nm(it.get("rarity")) or "—",
        "attune": bool(it.get("requires_attunement")),
        "attuneDesc": (it.get("attunement_detail") or "").strip(),
        "type": nm(it.get("category")),
        "blurb": blurb,
        "desc": desc,
    }


def v2_species(sp, all_species):
    traits = sp.get("traits") or []
    size, speed = "Medium", 30
    strings = []
    for t in traits:
        tname, tdesc = t.get("name", ""), (t.get("desc") or "").strip()
        if t.get("type") == "SIZE":
            size = (tdesc.split("(")[0] or "Medium").strip()
            continue
        if t.get("type") == "SPEED":
            mnum = re.search(r"(\d+)", tdesc)
            if mnum:
                speed = int(mnum.group(1))
            continue
        strings.append(f"{tname}. {tdesc}" if tdesc else tname)

    key = sp.get("key")
    subraces = []
    for child in all_species:
        parent = child.get("subspecies_of")
        pkey = parent.get("key") if isinstance(parent, dict) else parent
        if child.get("is_subspecies") and pkey == key:
            subraces.append({
                "name": child["name"],
                "asiText": "",
                "blurb": first_sentence(child.get("desc") or ""),
                "traits": [f"{t.get('name','')}. {(t.get('desc') or '').strip()}"
                           for t in (child.get("traits") or [])],
            })
    blurb = first_sentence(sp.get("desc") or "") or (first_sentence(strings[0]) if strings else "")
    return {
        "name": sp["name"],
        "size": size,
        "speed": speed,
        "asiText": "Ability scores come from your background (2024 rules)",
        "blurb": blurb,
        "traits": strings,
        "subraces": subraces,
    }


def v2_class(c, all_classes):
    long2short = {"Strength": "str", "Dexterity": "dex", "Constitution": "con",
                  "Intelligence": "int", "Wisdom": "wis", "Charisma": "cha"}

    def feat_list(raw):
        out = []
        for f in raw or []:
            levels = sorted({g.get("level") for g in (f.get("gained_at") or []) if g.get("level")}) or [1]
            out.append({"lvl": levels[0], "name": f.get("name", ""), "text": (f.get("desc") or "").strip()})
        out.sort(key=lambda x: (x["lvl"], x["name"]))
        return out

    key = c.get("key")
    subclasses = []
    for child in all_classes:
        parent = child.get("subclass_of")
        pkey = parent.get("key") if isinstance(parent, dict) else parent
        if pkey == key:
            feats = feat_list(child.get("features"))
            subclasses.append({
                "name": child["name"],
                "blurb": first_sentence(child.get("desc") or "") or (feats[0]["text"][:160] if feats else ""),
                "features": feats,
            })

    hd = c.get("hit_dice") or "D8"
    hd_num = int(re.sub(r"\D", "", hd) or 8)
    saves = [long2short.get(s.get("name"), "") for s in (c.get("saving_throws") or [])]
    return {
        "name": c["name"],
        "hd": hd_num,
        "primary": [long2short.get(nm(p), nm(p)) for p in (c.get("primary_abilities") or [])],
        "saves": [s for s in saves if s],
        "armor": [],
        "weapons": [],
        "equipment": [],
        "blurb": first_sentence(c.get("desc") or ""),
        "features": feat_list(c.get("features")),
        "subclasses": subclasses,
    }


def v2_background(b):
    skills, feature, asi, equip = [], "", "", ""
    for ben in b.get("benefits") or []:
        t, d = ben.get("type"), (ben.get("desc") or "").strip()
        if t == "skill_proficiencies":
            skills = [s.strip() for s in re.split(r",| and ", d) if s.strip()]
        elif t == "feat":
            feature = f"Feat: {d}"
        elif t == "ability_score":
            asi = d
        elif t == "equipment":
            equip = d
    blurb = first_sentence(b.get("desc") or "") or (f"Ability scores: {asi}." if asi else "")
    return {
        "name": b["name"],
        "skills": skills,
        "tools": [],
        "languages": "",
        "feature": feature,
        "blurb": blurb,
        "desc": (b.get("desc") or "").strip() or "\n".join(
            f"{ben.get('name','')}: {ben.get('desc','')}" for ben in (b.get("benefits") or [])),
    }


def v2_feat(f):
    benefits = [b.get("desc", "").strip() for b in (f.get("benefits") or []) if b.get("desc")]
    desc = (f.get("desc") or "").strip()
    if benefits:
        desc = (desc + "\n\n" if desc else "") + "\n".join(f"• {b}" for b in benefits)
    return {
        "name": f["name"],
        "prerequisite": (f.get("prerequisite") or "").strip(),
        "blurb": first_sentence(f.get("desc") or (benefits[0] if benefits else "")),
        "desc": desc,
    }


def v2_weapon(w, item_lookup):
    props = []
    for p in w.get("properties") or []:
        prop = p.get("property") or {}
        pname = prop.get("name", "")
        if prop.get("type") == "Mastery":
            pname += " (Mastery)"
        if p.get("detail"):
            pname += f" ({p['detail']})"
        if pname:
            props.append(pname)
    cat = ("Simple" if w.get("is_simple") else "Martial") + (" Ranged" if (w.get("range") or 0) > 5 else " Melee")
    dmg = f"{w.get('damage_dice') or ''} {nm(w.get('damage_type')).lower()}".strip()
    it = item_lookup.get(w["name"].lower(), {})
    return {
        "name": w["name"],
        "cat": cat,
        "dmg": dmg or "—",
        "props": ", ".join(props) if props else "—",
        "weight": it.get("weight", "—"),
        "cost": it.get("cost", "—"),
    }


def v2_armor(a, item_lookup):
    it = item_lookup.get(a["name"].lower(), {})
    return {
        "name": a["name"],
        "cat": title_case(a.get("category") or ""),
        "ac": a.get("ac_display") or str(a.get("ac_base", "?")),
        "stealth": "Disadvantage" if a.get("grants_stealth_disadvantage") else "—",
        "weight": it.get("weight", "—"),
        "cost": it.get("cost", "—"),
        "strReq": a.get("strength_score_required"),
    }


def fmt_money(c):
    try:
        v = float(c or 0)
    except (TypeError, ValueError):
        return "—"
    if v <= 0:
        return "—"
    return (f"{v:.2f}".rstrip("0").rstrip(".")) + " gp"


def fmt_weight(w):
    try:
        v = float(w or 0)
    except (TypeError, ValueError):
        return "—"
    return (f"{v:.3f}".rstrip("0").rstrip(".") + " lb") if v > 0 else "—"


def v2_gear(it):
    desc = (it.get("desc") or "").strip()
    blurb = first_sentence(desc, 200)
    return {
        "name": it["name"],
        "type": nm(it.get("category")) or "Adventuring Gear",
        "cost": fmt_money(it.get("cost")),
        "weight": fmt_weight(it.get("weight")),
        "blurb": blurb,
        "desc": desc,
    }


def v2_itemset(s):
    contents = ", ".join(i.get("name", "") for i in (s.get("items") or []))
    desc = (s.get("desc") or "").strip()
    if contents:
        desc = (desc + "\n\n" if desc else "") + f"Contents: {contents}."
    return {
        "name": s["name"],
        "type": "Equipment Set",
        "cost": "—",
        "weight": "—",
        "blurb": first_sentence(s.get("desc") or f"Contents: {contents}.", 200),
        "desc": desc,
    }


def v2_rule(r):
    parent = (r.get("ruleset") or "").replace("srd-2024_", "").replace("-", " ")
    return {
        "name": r["name"],
        "parent": title_case(parent),
        "desc": (r.get("desc") or "").strip(),
        "blurb": first_sentence(r.get("desc") or "", 240),
    }


# ─── Fetch drivers ──────────────────────────────────────────────────────────

def fetch_v1_packs():
    """Fetch all v1 endpoints (all documents), group by document, transform."""
    packs = {}
    licenses = {}

    def one(ep):
        sys.stderr.write(f"  v1/{ep}:\n")
        return ep, fetch_all(f"{API1}/{ep}/?limit=500")

    with ThreadPoolExecutor(max_workers=4) as ex:
        results = dict(ex.map(one, V1_ENDPOINTS))

    for ep, rows in results.items():
        cat = V1_ENDPOINTS[ep]
        tf = V1_TRANSFORMS[ep]
        for raw in rows:
            slug = raw.get("document__slug") or ""
            if slug in ("", "wotc-srd") or slug not in PACK_INFO:
                continue  # core SRD lives in srd-bulk.js; unknown docs skipped
            if slug not in licenses and raw.get("document__license_url"):
                licenses[slug] = raw["document__license_url"]
            entry = tf(raw)
            entry["source"] = slug
            entry["pack"] = slug
            packs.setdefault(slug, {}).setdefault(cat, []).append(entry)
    return packs, licenses


def fetch_v2_srd2024():
    key = "srd-2024"

    def doc_key(r):
        d = r.get("document")
        if isinstance(d, dict):
            return d.get("key") or ""
        return str(d or "").rstrip("/").rsplit("/", 1)[-1]  # plain key or URL form

    def grab(ep):
        sys.stderr.write(f"  v2/{ep}:\n")
        # Filter param naming is inconsistent across v2 endpoints (magicitems
        # honours `document`, creatures honours `document__key`); send both —
        # each endpoint applies the one it knows and ignores the other.
        rows = fetch_all(f"{API2}/{ep}/?document={key}&document__key={key}&limit=500")
        # Belt-and-braces: verify per entry in case an endpoint ignores both.
        return [r for r in rows
                if doc_key(r) == key or str(r.get("key", "")).startswith(key)]

    eps = ["creatures", "spells", "magicitems", "items", "species", "classes",
           "backgrounds", "feats", "weapons", "armor", "rules"]
    with ThreadPoolExecutor(max_workers=4) as ex:
        raw = dict(zip(eps, ex.map(grab, eps)))

    # cost/weight live on /v2/items — join onto weapons & armor by name
    item_lookup = {}
    for it in raw["items"]:
        w = it.get("weight")
        c = it.get("cost")
        item_lookup[it["name"].lower()] = {
            "weight": (w.rstrip("0").rstrip(".") + " lb") if isinstance(w, str) and float(w or 0) > 0 else "—",
            "cost": (c.rstrip("0").rstrip(".") + " gp") if isinstance(c, str) and float(c or 0) > 0 else "—",
        }

    species = raw["species"]
    classes = raw["classes"]
    data = {
        "monsters":    [v2_creature(m) for m in raw["creatures"]],
        "spells":      [v2_spell(s) for s in raw["spells"]],
        "items":       [v2_magicitem(i) for i in raw["magicitems"]],
        "gear":        [v2_gear(i) for i in raw["items"]],
        "races":       [v2_species(sp, species) for sp in species if not sp.get("is_subspecies")],
        "classes":     [v2_class(c, classes) for c in classes if not c.get("subclass_of")],
        "backgrounds": [v2_background(b) for b in raw["backgrounds"]],
        "feats":       [v2_feat(f) for f in raw["feats"]],
        "weapons":     [v2_weapon(w, item_lookup) for w in raw["weapons"]],
        "armor":       [v2_armor(a, item_lookup) for a in raw["armor"]],
        "sections":    [v2_rule(r) for r in raw["rules"]],
    }
    for cat, rows in data.items():
        for e in rows:
            e["source"] = key
            e["pack"] = key
    return {key: data}


def existing_item_names():
    """Names of magic items already shipped in srd-bulk.js (the v1 5.1 import),
    so the srd-2014-x variant pack only adds genuinely new entries."""
    bulk = HERE / "srd-bulk.js"
    names = set()
    if bulk.exists():
        txt = bulk.read_text(encoding="utf-8")
        m = re.search(r"window\.SRD_BULK = (\{.*?\});\n\n\(function", txt, re.DOTALL)
        if m:
            try:
                names = {e["name"].lower() for e in json.loads(m.group(1)).get("items", [])}
            except Exception:
                pass
    return names


def fetch_srd2014_extras():
    """Official 5.1 content the v1 API never exposed: mundane gear, equipment
    sets, and the fully-enumerated magic-item variants."""
    key = "srd-2014"

    def doc_key(r):
        d = r.get("document")
        if isinstance(d, dict):
            return d.get("key") or ""
        return str(d or "").rstrip("/").rsplit("/", 1)[-1]

    def grab(ep):
        sys.stderr.write(f"  v2/{ep} ({key}):\n")
        rows = fetch_all(f"{API2}/{ep}/?document={key}&document__key={key}&limit=500")
        return [r for r in rows if doc_key(r) == key or str(r.get("key", "")).startswith("srd_")]

    gear = [v2_gear(i) for i in grab("items")]
    # Equipment packs exist both as items (cost/weight) and itemsets (contents);
    # merge contents into the matching item, append only true standalone sets.
    by_name = {g["name"].lower(): g for g in gear}
    for s in grab("itemsets"):
        e = v2_itemset(s)
        hit = by_name.get(e["name"].lower())
        if hit:
            hit["desc"] = (hit["desc"] + "\n\n" if hit["desc"] else "") + e["desc"]
            if not hit["blurb"]:
                hit["blurb"] = e["blurb"]
        else:
            gear.append(e)
    have = existing_item_names()
    variants = [v2_magicitem(i) for i in grab("magicitems")]
    variants = [v for v in variants if v["name"].lower() not in have]
    sys.stderr.write(f"  srd-2014-x: {len(gear)} gear, {len(variants)} new item variants\n")

    data = {"gear": gear, "items": variants}
    for cat, rows in data.items():
        for e in rows:
            e["source"] = "srd-2014"
            e["pack"] = "srd-2014-x"
    return {"srd-2014-x": data}


def fetch_v2_spell_doc(key):
    """Spells-only v2 documents (e.g. spells-that-dont-suck)."""

    def doc_key(r):
        d = r.get("document")
        if isinstance(d, dict):
            return d.get("key") or ""
        return str(d or "").rstrip("/").rsplit("/", 1)[-1]

    sys.stderr.write(f"  v2/spells ({key}):\n")
    rows = fetch_all(f"{API2}/spells/?document={key}&document__key={key}&limit=500")
    rows = [r for r in rows if doc_key(r) == key or str(r.get("key", "")).startswith(key)]
    spells = [v2_spell(s) for s in rows]
    for e in spells:
        e["source"] = key
        e["pack"] = key
    return {key: {"spells": spells}}


# ─── Output ─────────────────────────────────────────────────────────────────

def render_pack_js(pack_id, data):
    label, group, badge, edition = PACK_INFO[pack_id]
    meta = {"id": pack_id, "label": label, "group": group, "badge": badge, "edition": edition}
    return (
        "/* auto-generated by data/fetch-packs.py — DO NOT EDIT BY HAND. */\n"
        "window.CODEX_PACKS = window.CODEX_PACKS || {};\n"
        f"window.CODEX_PACKS[{json.dumps(pack_id)}] = {{\n"
        f"  meta: {json.dumps(meta, ensure_ascii=False)},\n"
        f"  data: {json.dumps(data, ensure_ascii=False, separators=(',', ':'))}\n"
        "};\n"
        f"if (window.__onPackLoaded) window.__onPackLoaded({json.dumps(pack_id)});\n"
    )


V2_SPELL_DOCS = ["spells-that-dont-suck"]


def load_existing_manifest(out_dir):
    """Parse the committed manifest.js back into a list (for --only runs)."""
    mpath = out_dir / "manifest.js"
    if not mpath.exists():
        return []
    txt = mpath.read_text(encoding="utf-8")
    return json.loads(txt.split("=", 1)[1].rstrip().rstrip(";"))


def main():
    out_dir = HERE / "packs"
    out_dir.mkdir(exist_ok=True)

    # --only <id>[,<id>…]: refetch just those packs, keep the rest of the
    # manifest as committed. A run with no flag rebuilds everything.
    only = None
    if "--only" in sys.argv:
        only = set(sys.argv[sys.argv.index("--only") + 1].split(","))

    packs = {}
    licenses = {"srd-2024": "https://creativecommons.org/licenses/by/4.0/"}

    if only is None or "srd-2024" in only:
        sys.stderr.write("Fetching Open5e v2 — SRD 5.2 (D&D 2024)…\n")
        packs.update(fetch_v2_srd2024())
    if only is None or "srd-2014-x" in only:
        sys.stderr.write("Fetching Open5e v2 — SRD 5.1 gear & item variants…\n")
        packs.update(fetch_srd2014_extras())
        licenses.setdefault("srd-2014-x", "https://creativecommons.org/licenses/by/4.0/")
    for key in V2_SPELL_DOCS:
        if only is None or key in only:
            sys.stderr.write(f"Fetching Open5e v2 — {key}…\n")
            packs.update(fetch_v2_spell_doc(key))
            licenses.setdefault(key, "https://creativecommons.org/licenses/by/4.0/")
    v1_wanted = [s for s in PACK_ORDER if s not in ("srd-2024", "srd-2014-x", *V2_SPELL_DOCS)]
    if only is None or any(s in only for s in v1_wanted):
        sys.stderr.write("Fetching Open5e v1 — all expansion documents…\n")
        v1_packs, v1_licenses = fetch_v1_packs()
        if only is not None:
            v1_packs = {k: v for k, v in v1_packs.items() if k in only}
        packs.update(v1_packs)
        licenses.update(v1_licenses)

    manifest = load_existing_manifest(out_dir) if only is not None else []
    for pack_id in PACK_ORDER:
        data = packs.get(pack_id)
        if not data or not any(data.values()):
            continue
        data = {cat: rows for cat, rows in data.items() if rows}
        js = render_pack_js(pack_id, data)
        path = out_dir / f"{pack_id}.js"
        path.write_text(js, encoding="utf-8")
        label, group, badge, edition = PACK_INFO[pack_id]
        counts = {cat: len(rows) for cat, rows in data.items()}
        manifest = [m for m in manifest if m["id"] != pack_id]  # replace on --only reruns
        manifest.append({
            "id": pack_id, "label": label, "group": group, "badge": badge,
            "edition": edition, "file": f"data/packs/{pack_id}.js",
            "counts": counts, "kb": round(path.stat().st_size / 1024),
            "license": licenses.get(pack_id, ""),
        })
        sys.stderr.write(f"  wrote {path.name:18} {path.stat().st_size:>9,} B  {counts}\n")

    manifest.sort(key=lambda m: PACK_ORDER.index(m["id"]) if m["id"] in PACK_ORDER else 99)
    mpath = out_dir / "manifest.js"
    mpath.write_text(
        "/* auto-generated by data/fetch-packs.py — DO NOT EDIT BY HAND. */\n"
        f"window.CODEX_PACK_MANIFEST = {json.dumps(manifest, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    total = sum(m["kb"] for m in manifest)
    sys.stderr.write(f"\nWrote {mpath} — {len(manifest)} packs, {total:,} KB total.\n")


if __name__ == "__main__":
    main()
